camel:
  rest:
    binding-mode: json
    data-format-property:
      prettyPrint: true
    enable-cors: false
    port: "8080"
    api-context-path: "/api-doc"
    api-property:
      api.title: "User API"
      api.version: "1.0.0"
  servlet:
    mapping:
      context-path: "/api/*"
  dataformat:
    jaxb:
      object-factory: true
      fragment: true
      pretty-print: true
app:
  features:
    soap-route-builder-enabled: false
    soap-lambda-route-builder-enabled: true