camel:
  rest:
    binding-mode: json
    data-format-property:
      prettyPrint: true
    enable-cors: false
    port: "8080"
    api-context-path: "/api-doc"
    api-property:
      api.title: "User API"
      api.version: "1.0.0"
  servlet:
    mapping:
      context-path: "/api/*"
  dataformat:
    jaxb:
      object-factory: true
      fragment: true
      pretty-print: true
    jackson-xml:
      enable-jaxb-annotation-module: true
      pretty-print: true
  component:
    activemq:
      concurrent-consumers: 10
      max-concurrent-consumers: 20
      async-consumer: true
      transacted: true
app:
  features:
    soap-route-builder-enabled: false
    soap-lambda-route-builder-enabled: true
tracing:
  url: http://localhost:4318/v1/traces
jms:
  redelivery:
    initial-redelivery-delay: 5000
    backoff-multiplier: 2
    maximum-redeliveries: -1
    maximum-redelivery-delay: 30000
server:
  port: 8090
